apps/belt1_app/urls.py
from django.conf.urls import url, include
# from django.contrib import admin
from .import views
urlpatterns = [
    url(r'^$',views.index,name="index"),
    url(r'^additem$',views.additem,name="additem"),
    url(r'^addtowishlist/(?P<id>\d+)$',views.addtowishlist,name="addtowishlist"),
    url(r'^removefromwishlist/(?P<id>\d+)$',views.removefromwishlist,name="removefromwishlist"),
    url(r'^deleteprod/(?P<id>\d+)$',views.deleteprod,name="deleteprod"),
    url(r'^logout$',views.logout,name="logout"),
    url(r'^goback$',views.goback,name="goback"),
    url(r'^show_product/(?P<id>\d+)$',views.show_product,name="show_product"),

]

apps/user_app/urls.py
from django.conf.urls import url, include
# from django.contrib import admin
from .import views
urlpatterns = [
    url(r'^$',views.index,name="index"),
    url(r'^register$',views.register,name="register"),
    url(r'^login$',views.login,name="login"),
]

python_beltexam/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^',include('apps.user_app.urls',namespace="user")),
    url(r'^belt/',include('apps.belt1_app.urls',namespace="belt")),

]

apps/belt1_app/models.py
from __future__ import unicode_literals

from django.db import models
from ..user_app.models import User
# Create your models here.
class ProductManager(models.Manager):
    def validate_product(self,param,user):
        errors=[]
        if len(param['prod_name'])<1:
            errors.append("product cannot be blank")
        if len(param['prod_name'])<3:
            errors.append("Too short product name")
        if len(errors)>0:
            return (False,errors)
        else:
            print "True"
            self.create(prod_name=param['prod_name'],user=user)
            return (True,True)

class Product(models.Model):
    prod_name=models.CharField(max_length=50)
    user = models.ForeignKey(User,related_name="mywishlist")
    join = models.ManyToManyField(User,related_name="joined_user")
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    objects= ProductManager()

apps/user_app/models.py
from __future__ import unicode_literals

from django.db import models
import re
import bcrypt
import datetime
# Create your models here.
class UserManager(models.Manager):
    def validate(self,user):
        errors=[]
        user1=User.objects.filter(username=user['username'])
        name_regex = re.compile(r'^[a-zA-Z]+$')
        username_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+$')
        if len(user['fname'])<3 and not name_regex.match(user['fname']):
            print "false name"
            errors.append("Invalid name or too short")
        if len(user['username'])<1:
            errors.append("username cannot be blank!")
        if not username_REGEX.match(user['username']) and len(user['username'])<3:
            print "false username"
            errors.append("Invalid username or too short !")
        if len(user['password']) <8:
            print "false password"
            errors.append("too short password")
        if not user['cpassword'] == user['password']:
            # print user['password']
            # print user['cpassword']
            print "false confirm password"
            errors.append("password and confirm password do not match")
        if user['datehired'] < str(datetime.date.today()) and len(user['datehired']) <1:
            print "wrong date"
            errors.append("date hired cannot be back dated or empty")
        if user1:
            errors.append("username already taken !")
        if len(errors)>0:
            return (False,errors)
        else:
            print "true"
            # print user
            pass2=user['password']
            pass3=pass2.encode()
            hashed= bcrypt.hashpw(pass3,bcrypt.gensalt())
            # print hashed
            # pass1= bcrypt.hashpw(pass3,hashed)
            # print pass1
            User.objects.create( name=user['fname'],username=user['username'],Password=hashed)
            return (True,user)
    def login(self,user):
        print user
        user_log=self.filter(username=user['username'])
        if user_log:
            print user_log
            pass2=user['Password']
            pass3=pass2.encode()
            if bcrypt.hashpw(pass3,user_log[0].Password.encode())== user_log[0].Password:
                print user_log[0].id
                return {'user':user_log[0]}
            # else:
        return{'error':"username or password failed"}


class User(models.Model):
    name= models.CharField(max_length=50)
    username= models.CharField(max_length=50)
    Password= models.CharField(max_length=255)
    datehired =models.DateField(null=True)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)




    objects=UserManager()

apps/belt1_app/views.py
from django.shortcuts import render,redirect
from ..user_app .models import User
from .models import Product
from django.contrib import messages
# Create your views here.
def index(request):
    context={
    'msg': "redirected from add item also",
    'products':Product.objects.all(),
    'user':User.objects.get(id=request.session['userid'])
    }
    return render(request,"belt1_app/index.html",context)
def additem(request):
    if request.method == "POST":
        user=User.objects.get(id=request.session['userid'])
        valid=Product.objects.validate_product(request.POST,user)
        if valid[0] == False:
            print "false"
            print_messages(request, valid[1])
            return redirect('belt:additem')
        else:
            return redirect('belt:index')
    else:
        return render(request,"belt1_app/additem.html")
def print_messages(request, message_list):
    for message in message_list:
        messages.add_message(request, messages.INFO, message)
def addtowishlist(request,id):
    this_product=Product.objects.get(id=id)
    this_user=User.objects.get(id=request.session['userid'])
    this_product.join.add(this_user)
    return redirect('belt:index')
def removefromwishlist(request,id):
    this_product=Product.objects.get(id=id)
    this_user=User.objects.get(id=request.session['userid'])
    this_product.join.remove(this_user)
    return redirect('belt:index')
def deleteprod(request,id):
    this_product=Product.objects.get(id=id)
    this_product.delete()
    return redirect('belt:index')
def logout(request):
    request.session.clear()
    return redirect('user:index')
def goback(request):
    return redirect('belt:index')
def show_product(request,id):
    context={
    'prods':Product.objects.get(id=id)

    }
    return render(request,"belt1_app/show.html",context)

apps/user_app/views.py
from django.shortcuts import render,redirect
from .models import User
from django.contrib import messages
# Create your views here.
def index(request):
    return render(request,"user_app/index.html")
def register(request):
    if request.method == "POST":
        user1={
        'fname':request.POST['name'],
        'username':request.POST['username'],
        'password':request.POST['Password'],
        'cpassword':request.POST['cpassword'],
        'datehired':request.POST['datehired'],
        }
        user=User.objects.validate(user1)
        if user[0] == False:
            print "false"
            print_messages(request, user[1])
            return redirect('user:index')
        else:
            context={
            'msg':"you have successfully registered",
            }
            return render(request,"user_app/index.html",context)
    # else:
    #     return redirect('/')
def login(request):
    if request.method == "POST":

        user=User.objects.login(request.POST)
        # print type(user)
        if 'error' in user:
            print user['error']
            context={
                'errors':user['error']
            }
            return render(request,"user_app/index.html",context)
        else:

            request.session['name']=user['user'].name
            request.session['userid']=user['user'].id
        return redirect("belt:index")
def print_messages(request, message_list):
    for message in message_list:
        messages.add_message(request, messages.INFO, message)

apps/belt1_app/templates/belt1_app/additem.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    welcome to add item
    <h1>Create a new wishlist product</h1>
    <form  action="{% url 'belt:additem' %}" method="post">
      {% csrf_token %}
      Item/Product: <input type="text" name="prod_name" >
      <input type="submit" value="Add Item">

    </form>
    {% if messages %}
   <ul class="messages">
     {% for message in messages %}
     <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
     {% endfor %}
   </ul>
   {% endif %}
   <p>
     <a href="{% url 'belt:goback' %}">Home</a>
    <a href="{% url 'belt:logout' %}">LogOut</a>
   </p>
  </body>
</html>

apps/belt1_app/templates/belt1_app/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    welcome to belt index
    <h1>Welcome login {{request.session.name}} {{request.session.userid}}</h1>
    <a href="{% url 'belt:additem' %}">Add Item</a>
    <a href="{% url 'belt:logout' %}">LogOut</a>
    <h1>My wishlist</h1>
    <table>
      <thead>
        <th>
          product
        </th>
        <th>
          added by
        </th>
        <th>
          added date
        </th>
        <th>
          actions
        </th>
      </thead>
      <tbody>
        {%for product in products %}
        {% if product.user.id == request.session.userid or user in product.join.all %}
        <tr>
          <td>
            <a href="{% url 'belt:show_product' id=product.id %}">{{product.prod_name}}</a>
          </td>
          <td>
            {{product.user.username}}
          </td>
          <td>
            {{product.created_at}}
          </td>
          <td>
            {% if product.user.id == request.session.userid %}
            <a href="{% url 'belt:deleteprod' id=product.id %}">delete</a>
            {% else %}
            <a href="{% url 'belt:removefromwishlist' id=product.id %}">remove from my list</a>
            {% endif %}
          </td>
        </tr>
        {% endif %}
        {% endfor %}
      </tbody>
    </table>
    <h1>other users wishlist</h1>
    <table>
      <thead>
        <th>
          product
        </th>
        <th>
          added by
        </th>
        <th>
          added date
        </th>
        <th>
          actions
        </th>
      </thead>
      <tbody>
        {%for product in products %}
        {% if not product.user.id == request.session.userid and user not in product.join.all%}
        <tr>
          <td>
          <a href="{% url 'belt:show_product' id=product.id %}">{{product.prod_name}}</a>
          </td>
          <td>
            {{product.user.username}}
          </td>
          <td>
            {{product.created_at}}
          </td>
          <td>
            <a href="{% url 'belt:addtowishlist' id=product.id %}">add to my wishlist</a>
          </td>
        </tr>
        {% endif %}
        {% endfor %}
      </tbody>
    </table>

  </body>
</html>

apps/belt1_app/templates/belt1_app/show.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h3>
      product: {{prods.prod_name}}

    </h3>
    <h3>
      Added by:{{prods.user.username}}

    </h3>
    <h4>other Users who added this product to their wishlist</h4>

    <table>

    {% for user in prods.join.all %}
    <tr>

    <td>

    {{user.username}}
  </td>
</tr>
    {% endfor %}

  </table>

    <p>
      <a href="{% url 'belt:goback' %}">Home</a>
     <a href="{% url 'belt:logout' %}">LogOut</a>
    </p>

  </body>
</html>

apps/user_app/templates/user_app/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <p>
      welcome
    </p>
    <h3>Register</h3>
    <form  action="{% url 'user:register' %}" method="post">
      {% csrf_token %}
      name<input type="text" name="name">
      username <input type="text" name="username" >
      Password <input type="Password" name="Password" >
      Confirm Password: <input type="Password" name="cpassword">
      Date hired: <input type="date" name="datehired" >
      <input type="submit"  value="Register">
    </form>

    <p>
      {% if messages %}
     <ul class="messages">
       {% for message in messages %}
       <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
       {% endfor %}
     </ul>
     {% endif %}
    </p>
    <p>
      {{msg}}
    </p>
    <h3>Login</h3>
    <form class="" action="{% url 'user:login' %}" method="post">
      {% csrf_token %}
      username:<input type="text" name="username" >
      Password: <input type="password" name="Password" >
      <input type="submit" value="Login">
    </form>


  </body>
</html>

apps/user_app/templates/user_app/success.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    welcome user

  </body>
</html>